project:
  type: website

website:
  title: "Bloch Hole"
  site-url: https://cncastillo.github.io/BlochHole
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cncastillo/BlochHole/
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: right
    theme:
      - cosmo
    css: styles.css
comments:
  giscus: 
    repo: cncastillo/BlochHole
