project:
  type: website

website:
  title: "Bloch Hole"
  site-url: https://cncastillo.github.io/BlochHole
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cncastillo
      - icon: twitter
        href: https://x.com/Carlos_CP92
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css

comments:
  giscus: 
    repo: cncastillo/BlochHole



