project:
  type: website

website:
  title: "Bloch Hole"
  site-url: https://cncastillo.github.io/BlochHole
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://cncastillo.github.io/BlochHole/
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
comments:
  giscus: 
    repo: cncastillo/BlochHole
listing:
  contents: posts
  fields: [image, date, title, description, reading-time, author]



