project:
  type: website

website:
  title: "Bloch Hole - The fun side of serious science"
  site-url: https://cncastillo.github.io/BlochHole
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cncastillo/BlochHole/
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
comments:
  giscus: 
    repo: cncastillo/BlochHole
